[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  h2zero/NimBLE-Arduino @ ^1.4.2
build_src_filter =
  +<main.cpp>
  -<sim_main.cpp>
build_flags =
  -D CFG_SDA_PIN=21
  -D CFG_SCL_PIN=22
  -D CFG_MPU_ADDR=0x68
  -D CFG_PIN_LEFT_AMBER=5
  -D CFG_PIN_RIGHT_AMBER=18
  -D CFG_PIN_TAIL_RED=19

[env:esp32sim]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  h2zero/NimBLE-Arduino @ ^1.4.2
build_src_filter =
  -<main.cpp>
  +<sim_main.cpp>
build_flags =
  -D CFG_PIN_LEFT_AMBER=5
  -D CFG_PIN_RIGHT_AMBER=18
  -D CFG_PIN_TAIL_RED=19
