[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  h2zero/NimBLE-Arduino @ ^1.4.2
build_src_filter =
  +<main.cpp>
  -<sim_main.cpp>
build_flags =
  -D CFG_SDA_PIN=21
  -D CFG_SCL_PIN=22
  -D CFG_MPU_ADDR=0x68
  -D CFG_HEADLIGHT_LEFT_PIN=18
  -D CFG_HEADLIGHT_RIGHT_PIN=19
  -D CFG_TAIL_LEFT_PIN=25
  -D CFG_TAIL_RIGHT_PIN=26
  -D CFG_TURN_FRONT_LEFT_PIN=27
  -D CFG_TURN_FRONT_RIGHT_PIN=14
  -D CFG_TURN_REAR_LEFT_PIN=33
  -D CFG_TURN_REAR_RIGHT_PIN=32

[env:esp32sim]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  h2zero/NimBLE-Arduino @ ^1.4.2
build_src_filter =
  -<main.cpp>
  +<sim_main.cpp>
build_flags =
  -D CFG_HEADLIGHT_LEFT_PIN=18
  -D CFG_HEADLIGHT_RIGHT_PIN=19
  -D CFG_TAIL_LEFT_PIN=25
  -D CFG_TAIL_RIGHT_PIN=26
  -D CFG_TURN_FRONT_LEFT_PIN=27
  -D CFG_TURN_FRONT_RIGHT_PIN=14
  -D CFG_TURN_REAR_LEFT_PIN=33
  -D CFG_TURN_REAR_RIGHT_PIN=32
